//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WrightWayRestaurant.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailConfig
    {
        public int ConfigId { get; set; }
        public string EmailType { get; set; }
        public string EmailAcount { get; set; }
        public string EmailPassword { get; set; }
        public string EmailHost { get; set; }
        public Nullable<int> EmailPort { get; set; }
        public Nullable<bool> EmailState { get; set; }
        public Nullable<int> Sort { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
    
        public virtual SystemUser SystemUser { get; set; }
    }
}
