//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WrightWayRestaurant.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int DetailId { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> FoodId { get; set; }
        public Nullable<int> Number { get; set; }
    
        public virtual Food Food { get; set; }
        public virtual Order Order { get; set; }
    }
}
